# Generated by Django 3.2.5 on 2021-07-19 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20210719_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submitted_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
