# Generated by Django 3.2.5 on 2021-07-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20210721_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='image_aspect',
            field=models.CharField(choices=[('Labial', 'Labial'), ('Lingual', 'Lingual'), ('Mesial', 'Mesial'), ('Destial', 'Destial'), ('top view', 'top view')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='image_type',
            field=models.CharField(choices=[('type 1', 'type 1'), ('Others', 'Others')], max_length=20),
        ),
    ]
