# Generated by Django 3.2.5 on 2021-07-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20210721_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='processed_image',
            field=models.ImageField(blank=True, upload_to='processed'),
        ),
    ]
