# Generated by Django 3.2.5 on 2021-07-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_alter_assessment_processed_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=256)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='engine.assessment')),
            ],
        ),
    ]
