# Generated by Django 3.2.5 on 2021-10-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20210726_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='shape_match_image',
            field=models.ImageField(blank=True, upload_to='shape_match'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='image_aspect',
            field=models.CharField(choices=[('buccal', 'buccal'), ('lingual', 'lingual'), ('mesial', 'mesial'), ('distal', 'distal'), ('top_view', 'top_view')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='image_type',
            field=models.CharField(choices=[('mandipular', 'mandipular'), ('central', 'central')], max_length=20),
        ),
    ]
