# Generated by Django 3.2.5 on 2021-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20211023_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='image_type',
            field=models.CharField(choices=[('premandibular', 'premandibular'), ('central', 'central')], max_length=20),
        ),
    ]
