# Generated by Django 3.2.5 on 2022-02-02 11:54

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_alter_assessment_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stacktrace', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='errorlogs/stacktrace')),
                ('image', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='errorlogs/images')),
            ],
        ),
    ]
